"""added more features to the big five questionnaire

Revision ID: 0311421b52fb
Revises: 4bfce76af2e0
Create Date: 2020-04-22 09:48:42.871587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0311421b52fb'
down_revision = '4bfce76af2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('art', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('fault', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('imagination', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('job', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('lazy', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('nervous', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('relax', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('social', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('trust', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'trust')
    op.drop_column('user', 'social')
    op.drop_column('user', 'relax')
    op.drop_column('user', 'nervous')
    op.drop_column('user', 'lazy')
    op.drop_column('user', 'job')
    op.drop_column('user', 'imagination')
    op.drop_column('user', 'fault')
    op.drop_column('user', 'art')
    # ### end Alembic commands ###
