"""empty message

Revision ID: 05004bda70a7
Revises: b50d1610cc97
Create Date: 2020-08-15 08:17:55.282636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05004bda70a7'
down_revision = 'b50d1610cc97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('user', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_chat_timestamp'), 'global_chat', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_global_chat_timestamp'), table_name='global_chat')
    op.drop_table('global_chat')
    # ### end Alembic commands ###
