"""added last question to the final questionnaire

Revision ID: 093600f1509e
Revises: b2ae3dc5d9f8
Create Date: 2020-08-06 13:06:07.750723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093600f1509e'
down_revision = 'b2ae3dc5d9f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('satisfaction', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'satisfaction')
    # ### end Alembic commands ###
