"""empty message

Revision ID: 100daac051ad
Revises: 46e2a54017fc
Create Date: 2020-07-24 14:47:41.657156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100daac051ad'
down_revision = '46e2a54017fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('chat', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'chat')
    # ### end Alembic commands ###
