"""empty message

Revision ID: 3400609f8c2f
Revises: 0ee82f63fbc4
Create Date: 2020-08-07 09:53:44.639673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3400609f8c2f'
down_revision = '0ee82f63fbc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_timestamp', table_name='chat')
    op.drop_table('chat')
    op.add_column('message', sa.Column('chat', sa.String(length=140), nullable=True))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'sender_id')
    op.drop_column('message', 'body')
    op.drop_column('message', 'recipient_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('recipient_id', sa.INTEGER(), nullable=True))
    op.add_column('message', sa.Column('body', sa.VARCHAR(length=140), nullable=True))
    op.add_column('message', sa.Column('sender_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'message', 'user', ['recipient_id'], ['id'])
    op.create_foreign_key(None, 'message', 'user', ['sender_id'], ['id'])
    op.drop_column('message', 'chat')
    op.create_table('chat',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_timestamp', 'chat', ['timestamp'], unique=False)
    # ### end Alembic commands ###
