"""empty message

Revision ID: 3a87747d4fac
Revises: 6b42d2e834c8
Create Date: 2020-08-11 22:11:18.220954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a87747d4fac'
down_revision = '6b42d2e834c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('balance_extra', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('comments', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('improve', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('keep', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('other', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'other')
    op.drop_column('user', 'keep')
    op.drop_column('user', 'improve')
    op.drop_column('user', 'comments')
    op.drop_column('user', 'balance_extra')
    # ### end Alembic commands ###
