"""empty message

Revision ID: 46e2a54017fc
Revises: 9bbcfb0051dc
Create Date: 2020-07-24 13:35:16.737743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e2a54017fc'
down_revision = '9bbcfb0051dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('room', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'room')
    # ### end Alembic commands ###
