"""trying again to fix the crud

Revision ID: 4bfce76af2e0
Revises: e49d575a50a0
Create Date: 2020-04-20 21:13:02.825285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bfce76af2e0'
down_revision = 'e49d575a50a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_extraversion', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_extraversion', 'user', ['extraversion'], unique=1)
    # ### end Alembic commands ###
