"""empty message

Revision ID: 59e6b826cbec
Revises: 7b4865f30760
Create Date: 2020-08-07 08:52:15.986450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e6b826cbec'
down_revision = '7b4865f30760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('user', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'user')
    # ### end Alembic commands ###
