"""empty message

Revision ID: 6581a9cb6a48
Revises: 21c8bf9b9e5b
Create Date: 2020-06-09 14:28:34.176389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6581a9cb6a48'
down_revision = '21c8bf9b9e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('match', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'match')
    # ### end Alembic commands ###
