"""empty message

Revision ID: 760590b1235c
Revises: 11aef4caab30
Create Date: 2020-08-11 19:47:47.200168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760590b1235c'
down_revision = '11aef4caab30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), nullable=True))
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    # ### end Alembic commands ###
