"""empty message

Revision ID: 7dff4f3a9e39
Revises: c865654a9be7
Create Date: 2020-08-07 09:34:34.460610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dff4f3a9e39'
down_revision = 'c865654a9be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'chat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('chat', sa.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
