"""empty message

Revision ID: 854f29d9e408
Revises: c8ba1eb05d0b
Create Date: 2020-08-14 14:30:47.942978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854f29d9e408'
down_revision = 'c8ba1eb05d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('amt_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'amt_id')
    # ### end Alembic commands ###
