"""added end of task questions

Revision ID: b2ae3dc5d9f8
Revises: 100daac051ad
Create Date: 2020-08-04 14:20:30.141003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2ae3dc5d9f8'
down_revision = '100daac051ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('balance', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('cohesion', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('communication', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('performance', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'performance')
    op.drop_column('user', 'communication')
    op.drop_column('user', 'cohesion')
    op.drop_column('user', 'balance')
    # ### end Alembic commands ###
