"""empty message

Revision ID: c865654a9be7
Revises: 809b54521eb3
Create Date: 2020-08-07 09:33:28.245794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c865654a9be7'
down_revision = '809b54521eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'chat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('chat', sa.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
