"""empty message

Revision ID: c8ba1eb05d0b
Revises: 4e5a09d16319
Create Date: 2020-08-12 18:53:25.647970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ba1eb05d0b'
down_revision = '4e5a09d16319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('anxious', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('calm', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('careless', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('complex', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('critical', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('dependable', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('enthusiasm', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('reserved', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('uncreative', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('warm', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'warm')
    op.drop_column('user', 'uncreative')
    op.drop_column('user', 'reserved')
    op.drop_column('user', 'enthusiasm')
    op.drop_column('user', 'dependable')
    op.drop_column('user', 'critical')
    op.drop_column('user', 'complex')
    op.drop_column('user', 'careless')
    op.drop_column('user', 'calm')
    op.drop_column('user', 'anxious')
    # ### end Alembic commands ###
