"""empty message

Revision ID: d903d64e21af
Revises: b91db0c119e8
Create Date: 2020-08-07 09:36:40.859968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd903d64e21af'
down_revision = 'b91db0c119e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'chat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('chat', sa.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
