"""added extraversion

Revision ID: e49d575a50a0
Revises: b839f090d2ac
Create Date: 2020-04-20 20:50:02.007940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49d575a50a0'
down_revision = 'b839f090d2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('extraversion', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_extraversion'), 'user', ['extraversion'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_extraversion'), table_name='user')
    op.drop_column('user', 'extraversion')
    # ### end Alembic commands ###
