"""empty message

Revision ID: f703b3fdba55
Revises: 42ef4ab42fb4
Create Date: 2020-07-21 21:37:18.461420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f703b3fdba55'
down_revision = '42ef4ab42fb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('code', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'code')
    # ### end Alembic commands ###
